kind: Deployment
apiVersion: apps/v1
metadata:
  name: app2
  # these labels are deployment related labels
  labels:
    app: app2
    purpose: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      purpose: ingress
  # pod definition
  template:
    metadata: 
      labels:
        app: app2
        purpose: ingress
    spec:
      containers:
      - name: app2
        image: saipavan9594/app2:1.0

---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
    purpose: ingress
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port
          
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:533267158693:certificate/6f1de1e8-8353-4445-9188-168a3f15b605
    alb.ingress.kubernetes.io/listen-ports: '[ {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/group.name: expense
    # kubernetes cluster will create internet-facing, ip based load balancer with some tags and group.
spec:
  ingressClassName: alb
  rules:
  - host: "app2.pspkdevops.online" # ALB Rule
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2 # ALB Target group
            port:
              number: 80
